# github actions versions need updating periodically
# for the latest versions see: https://github.com/docker/build-push-action

name: Docker

on:
  push:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Runner disk space cleanup
        run: |
          echo "Before"
          df -h
          
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          echo "$AGENT_TOOLSDIRECTORY"
          df -h
          
          sudo rm -rf /usr/local/lib/android
          echo "android"
          df -h
          
          sudo rm -rf /opt/ghc
          echo "ghc"
          df -h
          
          echo "root"
          du -h --max-depth=1 /